[tool.poetry]
name = "gen"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["yukinarit <yukinari.tani@mapbox.com>"]

[tool.poetry.dependencies]
python = "^3.7"
holidays = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
